name: Host-Fonts
on:
  push:
    branches:
      - typo-fonts
jobs:
  setup:
    environment: typo-fonts
    name: Base setup
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Clone config repository
        uses: actions/checkout@v4
        with:
          ref: main
          repository: First-Peoples-Cultural-Council/fv-apps-config
          token: ${{ secrets.PULL_CONFIG_SECRET }}
          path: fv-apps-config
      - name: Set variables
        run: |
          mkdir modules
          mkdir typo-fonts
          ls -a;
          mv ./fv-apps-config/modules/*  ./modules/
          mv ./fv-apps-config/typo-fonts/*  ./typo-fonts/
          touch modules/prod.auto.tfvars
          printf "%s\n" "aws_profile = \"default\"" >> modules/prod.auto.tfvars 
          printf "%s\n" "domain = \"${{vars.DOMAIN}}\"" >> modules/prod.auto.tfvars 
          printf "%s\n" "application_name = \"${{vars.APPLICATION_NAME}}\"" >> modules/prod.auto.tfvars 
          printf "%s\n" "website_path  = \"${{vars.WEBSITE_PATH}}\"" >> modules/prod.auto.tfvars 
          cat >> modules/prod.auto.tfvars <<'EOF'
          subdomains = ${{ vars.SUBDOMAINS }}
          EOF
          printf "%s\n" "default_root_index_file = \"index.html\"" >> modules/prod.auto.tfvars
          printf "%s\n" "env_name = \"${{vars.ENV_NAME}}\"" >> modules/prod.auto.tfvars
          rm -rf modules/pre-prod-terraform.tf
          rm -rf modules/dev-terraform.tf
          rm -rf modules/prod-terraform.tf
          mv modules/host-fonts-terraform.tf modules/terraform.tf
          mkdir uploads
          mv modules/* uploads/
          mv typo-fonts uploads/typo-fonts
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: uploads
          path: uploads/
  #     - run: ls ;cd modules; ls;
  inspect_changes:
    environment: typo-fonts
    if: github.ref == 'refs/heads/typo-fonts'
    name: Inspect Infra Changes
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: hashicorp/setup-terraform@v3
      - uses: actions/download-artifact@v4
        with:
          name: uploads
          path: downloads/
      - name: Check directory files
        run: |
          ls
          mkdir modules
          mv downloads/* modules/
          cd modules
          ls
          cd typo-fonts
          ls
      - name: Terraform plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.FPCC_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.FPCC_AWS_SECRET_ACCESS_KEY }}
        run: |
          ls
          cd modules
          ls
          terraform init -lock=false
          terraform fmt
          terraform plan
  update_infra_changes:
    environment: typo-fonts
    name: Update Infra and App Changes
    runs-on: ubuntu-latest
    needs: inspect_changes
    if: github.ref == 'refs/heads/typo-fonts'
    steps:
      - uses: hashicorp/setup-terraform@v3
      - uses: actions/download-artifact@v4
        with:
          name: uploads
          path: downloads/
      - name: Check directory files
        run: |
          ls
          mkdir modules
          mv downloads/* modules/
          cd modules
          ls
          cd typo-fonts
          ls
      - name: Terraform plan and apply
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.FPCC_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.FPCC_AWS_SECRET_ACCESS_KEY }}
        run: |
          cd modules
          terraform init -lock=false
          terraform fmt
          terraform plan
          terraform apply -auto-approve -lock=false
          echo "Distro_ID=$(terraform output cloudfront_discribution)" >> "$GITHUB_ENV";
      - name: Invalidate cloudfront cache
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.FPCC_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.FPCC_AWS_SECRET_ACCESS_KEY }}
          AWS_EC2_METADATA_DISABLED: true
        run: |
          aws cloudfront create-invalidation --distribution-id ${{  env.Distro_ID  }} --paths "/*"
          echo "Invalidation_ID=$(aws cloudfront list-invalidations --distribution-id ${{  env.Distro_ID  }} | jq -c '.InvalidationList.Items | .[] | select(.Status | contains("InProgress")) | .Id' | head -n 1)" >> "$GITHUB_ENV";
      - name: Wait for invalidation completion
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.FPCC_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.FPCC_AWS_SECRET_ACCESS_KEY }}
          AWS_EC2_METADATA_DISABLED: true
        run: |
          aws cloudfront wait invalidation-completed --id ${{  env.Invalidation_ID  }} --distribution-id ${{  env.Distro_ID  }}
          echo "Deployment Completed"

